version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - revive
    - nolintlint
  settings:
    govet:
      enable:
        - nilness
        - reflectvaluecompare
        - sortslice
        - unusedwrite
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
